### ISSUE TITLE
Why does patcher use '--filesonly' argument?

### ISSUE THREAD

**Issue by JeremyStepp** [nwestfal/pylotro#10]
Does anyone know why the patcher uses the '--filesonly' argument? As far as I can tell it just stops it from doing all the updates that are usually needed to have an up to date game.

**Comment by JeremyStepp** [comment]
Since no one has responded and I don't see a reason not to, I have removed it from my version of the code.  It is private right now, but if anyone still uses pylotro and is interested I will share it. It includes a bunch of improvements including 64-bit client support.

**Comment by srukle** [comment]
@JeremyStepp I'm interested.

**Comment by JuneStepp** [comment]
@srukle Here is the repo: https://github.com/JuneStepp/OneLauncher

Also, for the sake of this thread I think using the --filesonly argument along with --dataonly can give a slight speed boost, because of needing to patch files twice. The data part got messed up somehow in my code, so I was getting issues.
